apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xdkir7t1o-nodejs
  janus-idp.io/tekton: xdkir7t1o-nodejs
  backstage.io/kubernetes-id: xdkir7t1o-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xdkir7t1o-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
