apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xdkir7t1o-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xdkir7t1o-nodejs 
  name: xdkir7t1o-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: xdkir7t1o-nodejs 
